language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
cache:
  directories:
    - $HOME/.gradle/wrapper/
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
deploy:
  provider: releases
  api_key: $key
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  name: Name?
  on:
    branch: master